name: Arnaud De Bruyn
favicon: null
layout_spectrum: 0.34022
typography_spectrum: 0.84177
title: "Arnaud De Bruyn's personal website"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#292d30'
    - '#9ea4a2'
    - '#f8dad0'
    - '#616b6c'
    - '#d69391'
  brandStrength: 0.3125
  lightness: 0.375
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
