name: Arnaud De Bruyn
favicon: null
layout_spectrum: 0.34022
typography_spectrum: 0.8569154548458755
title: "Arnaud De Bruyn's personal website"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#292d30'
    - '#9ea4a2'
    - '#f8dad0'
    - '#616b6c'
    - '#d69391'
  brandStrength: 0.2851588958874345
  lightness: 0.8990923266392201
  saturation: 0.9385426447261125
  rhythmicContrast: 0.14820188586600125
purpose: []
